function test(x: string | number, y: string | boolean) {
    if (x == y) {
        // We can now call any 'string' method on 'x' or 'y'.
        return x.toUpperCase() + y.toLowerCase();
    }
    return JSON.stringify([x, y]);
}

export function testEqualityNarrowing() {
    return [
        test("hello", "world"),
        test("hello", "hello"),
        test("hello", true),
        test(1, "hello"),
        test(1, true),
    ];
}
