import { testArray } from './Array.uts'
import { testDate } from './Date.uts'
import { testString } from './String.uts'
import { testError } from './Error.uts'
import { testKeyWord } from './KeyWord.uts'
// #ifndef APP-HARMONY
import { testJSON } from './JSON.uts'
import { testJSONLarge } from './JSON_large.uts'
import { testUTSJSONObject } from './UTSJSONObject.uts'
// #endif
import { testConsole } from './console.uts'
import { testNumber } from './Number.uts'
import { testMap } from './Map.uts'
import { testSet } from './Set.uts'
import { testOperators } from './Operators.uts'
import { testMath } from './Math.uts'
import { testRegExp } from './RegExp.uts'
import { testForLoop } from './ForLoop.uts'
import { testGlobal } from './Global.uts'
import { testType } from './Type.uts'
export { Result } from './tests.uts'
import { testNativeCode } from './NativeCode.uts'
import { testEncoder } from "./TextEncoder.uts"
import { testDecoder } from "./TextDecoder.uts"
// #ifndef APP-HARMONY
// 相关测试例有非常多的类型推断错误暂时屏蔽，https://issuereporter.developer.huawei.com/detail/250322170103030/comment
import { testArrayBuffer } from './ArrayBuffer.uts'
// TODO 确认鸿蒙对Promise的catch参数有何要求
import { testPromise } from "./Promise.uts"
// for of、for in在鸿蒙平台支持度欠佳，或许应该借助编译器拉齐？
import { testIterator } from "./iterator.uts"
// #endif
import { testUTSXXX } from "./UTSXXX.uts"

// Proxy、Reflect、Weakmap、WeakSet 不支持
export function runTests(): UTSJSONObject {
  const ArrayRes = testArray();
  const DateRes = testDate();
  const StringRes = testString();
  const ErrorRes = testError();
  const NumberRes = testNumber();
  const MapRes = testMap();
  const SetRes = testSet();
  const OperatorsRes = testOperators();
  const MathRes = testMath();
  const RegExpRes = testRegExp();
  const KeyWordRes = testKeyWord();
  const ForLoopRes = testForLoop();
  const GlobalRes = testGlobal();
  const TypeRes = testType();
  // #ifndef APP-HARMONY
  const JsonRes = testJSON();
  const JSONLargeRes = testJSONLarge();
  const UTSJSONObjectRes = testUTSJSONObject();
  // #endif
  const consoleRes = testConsole();
  const NativeCodeRes = testNativeCode();
  // #ifdef  APP-ANDROID || WEB
  const TextEncoderRes = testEncoder();
  const TextDecoderRes = testDecoder();
  // #endif
  // #ifndef APP-HARMONY
  const ArrayBufferRes = testArrayBuffer();
  const PromiseRes = testPromise();
  const IteratorRes = testIterator()
  // #endif
  const testUTSXXXRes = testUTSXXX()
  return {
    Array: ArrayRes,
    Date: DateRes,
    String: StringRes,
    Error: ErrorRes,
    Number: NumberRes,
    Map: MapRes,
    Set: SetRes,
    Operators: OperatorsRes,
    Math: MathRes,
    RegExp: RegExpRes,
    KeyWord: KeyWordRes,
    ForLoop: ForLoopRes,
    Global: GlobalRes,
    Type: TypeRes,
    console: consoleRes,
    // #ifndef APP-HARMONY
    ArrayBuffer: ArrayBufferRes,
    // #endif
    // #ifdef  APP-ANDROID || WEB
    TextEncoder: TextEncoderRes,
    TextDecoder: TextDecoderRes,
    // #endif
    NativeCode: NativeCodeRes,
    // #ifndef APP-HARMONY
    Primise: PromiseRes,
    Json: JsonRes,
    JSONLarge: JSONLargeRes,
    UTSJSONObject: UTSJSONObjectRes,
    Iterator: IteratorRes,
    // #endif
    UTSXXX: testUTSXXXRes,
  }
}