import {
  describe,
  test,
  expect,
  Result
} from './tests.uts'

export class TInt16Array {
  test() {
    // #ifdef (UNI-APP-X && APP-ANDROID) || WEB
    this.testConstructor();
    this.testSet();
    this.testCopyWith();
    this.testEvery();
    this.testFill();
    this.testFilter();
    this.find();
    this.findIndex();
    this.foreach();
    this.iterator();
    this.includes();
    this.indexOf();
    this.join();
    this.keys();
    this.map();
    this.reduce();
    this.reduceRight();
    this.reverse();
    this.slice();
    this.sort();
    this.subarray();
    this.values();
    this.arrayBufferSlice();
    // #endif
  }

  // #ifdef (UNI-APP-X && APP-ANDROID) || WEB

  testConstructor() {
    let buffer = new ArrayBuffer(16);
    let int16 = new Int16Array(buffer);
    int16[5] = 42;
    expect(int16.toString()).toEqual("0,0,0,0,0,42,0,0");
  }

  testSet() {
    // #TEST Int16Array.set
    let int16 = new Int16Array(8);
    var array = [1, 2, 3];
    int16.set(array, 1);
    expect(int16.toString()).toEqual("0,1,2,3,0,0,0,0");
    // #END
  }

  testCopyWith() {
    // #TEST Int16Array.copyWithin
    let int16 = new Int16Array(8);
    int16.set([1, 2, 3], 1);
    int16.copyWithin(3, 0, 3);
    expect(int16.toString()).toEqual("0,1,2,0,1,2,0,0");
    // #END
  }

  testEvery() {
    // #TEST Int16Array.every
    let result = new Int16Array([12, 5, 8, 130, 44]).every((value, _, _a : Int16Array) : boolean => value < 40);
    expect(result).toEqual(false);
    // #END
  }

  testFill() {
    // #TEST Int16Array.fill
    let int16 = new Int16Array([1, 2, 3]).fill(4);
    expect(int16.toString()).toEqual("4,4,4");

    int16 = new Int16Array([1, 2, 3]).fill(4, 1);
    expect(int16.toString()).toEqual("1,4,4");

    int16 = new Int16Array([1, 2, 3]).fill(4, 1, 2);
    expect(int16.toString()).toEqual("1,4,3");

    int16 = new Int16Array([1, 2, 3]).fill(4, 1, 1);
    expect(int16.toString()).toEqual("1,2,3");

    int16 = new Int16Array([1, 2, 3]).fill(4, -3, -2);
    expect(int16.toString()).toEqual("4,2,3");
    // #END
  }

  testFilter() {
    // #TEST Int16Array.filter
    let int16 = new Int16Array([12, 5, 8, 44]).filter((value, _, _a : Int16Array) : boolean => value >= 10);
    expect(int16.toString()).toEqual("12,44");
    // #END
  }

  find() {
    // #TEST Int16Array.find
    let int16 = new Int16Array([4, 5, 8, 12]);
    let res = int16.find((value, _, _a : Int16Array) : boolean => value > 5);
    expect(res).toEqual(8);
    // #END
  }

  findIndex() {
    // #TEST Int16Array.findIndex
    let int16 = new Int16Array([4, 6, 8, 12]);
    let res = int16.findIndex((value, _, _a : Int16Array) : boolean => value > 100);
    expect(res).toEqual(-1);

    int16 = new Int16Array([4, 6, 7, 120]);
    res = int16.findIndex((value, _, _a : Int16Array) : boolean => value > 100);
    expect(res).toEqual(3);
    // #END
  }

  foreach() {
    // #TEST Int16Array.forEach
    new Int16Array([0, 1, 2, 3]).forEach((value, index, _ : Int16Array) => {
      console.log(`a[${index}] = ${value}`);
    });
    // #END
  }

  iterator() {
    // #TEST Int16Array.entries
    let arr = new Int16Array([10, 20, 30, 40, 50]);
    let entries = arr.entries();
    expect(entries.next().value[1]).toEqual(10);
    // #END
  }

  includes() {
    // #TEST Int16Array.includes
    let int16 = new Int16Array([1, 2, 3]);
    let res = int16.includes(2);
    expect(res).toEqual(true);

    res = int16.includes(4);
    expect(res).toEqual(false);

    res = int16.includes(3, 3);
    expect(res).toEqual(false);
    // #END
  }

  indexOf() {
    // #TEST Int16Array.indexOf
    let int16 = new Int16Array([2, 5, 9]);
    let res = int16.indexOf(2);
    expect(res).toEqual(0);

    res = int16.indexOf(7);
    expect(res).toEqual(-1);

    res = int16.indexOf(9, 2);
    expect(res).toEqual(2);

    res = int16.indexOf(2, -1);
    expect(res).toEqual(-1);

    res = int16.indexOf(2, -3);
    expect(res).toEqual(0);
    // #END
  }

  join() {
    // #TEST Int16Array.join
    let int16 = new Int16Array([1, 2, 3]);
    let res = int16.join();
    expect(res).toEqual("1,2,3");

    res = int16.join(" / ");
    expect(res).toEqual("1 / 2 / 3");

    res = int16.join("");
    expect(res).toEqual("123");
    // #END
  }

  keys() {
    // #TEST Int16Array.keys
    let arr = new Int16Array([10, 20, 30, 40, 50]);
    let keys = arr.keys();
    expect(keys.next().value).toEqual(0);
    expect(keys.next().value).toEqual(1);
    expect(keys.next().value).toEqual(2);
    expect(keys.next().value).toEqual(3);
    expect(keys.next().value).toEqual(4);
    // #END
  }

  map() {
    // #TEST Int16Array.map
    let numbers = new Int16Array([1, 4, 9]);
    let doubles = numbers.map((value, _, _a : Int16Array) : number => value * 2);
    expect(numbers.toString()).toEqual("1,4,9");
    expect(doubles.toString()).toEqual("2,8,18");
    // #END
  }

  reduce() {
    // #TEST Int16Array.reduce
    let total = new Int16Array([0, 1, 2, 3]);
    let res = total.reduce((accumulator, currentValue, _, _a : Int16Array) : number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int16Array([0, 1, 2, 3]);
    res = total.reduce((accumulator, currentValue, _, _a : Int16Array) : number => accumulator + currentValue, 8);
    expect(res).toEqual(14);
    // #END
  }

  reduceRight() {
    // #TEST Int16Array.reduceRight
    let total = new Int16Array([0, 1, 2, 3]);
    let res = total.reduceRight((accumulator, currentValue, _, _a : Int16Array) : number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int16Array([0, 1, 2, 3]);
    res = total.reduceRight((accumulator, currentValue, _, _a : Int16Array) : number => accumulator + currentValue, 8);
    expect(res).toEqual(14);
    // #END
  }

  reverse() {
    // #TEST Int16Array.reverse
    let int16 = new Int16Array([1, 2, 3]);
    int16.reverse();
    expect(int16.toString()).toEqual("3,2,1");
    // #END
  }

  slice() {
    // #TEST Int16Array.slice
    let int16 = new Int16Array([1, 2, 3]);
    let res = int16.slice(1);
    expect(res.toString()).toEqual("2,3");

    res = int16.slice(2);
    expect(res.toString()).toEqual("3");

    res = int16.slice(-2);
    expect(res.toString()).toEqual("2,3");

    res = int16.slice(0, 1);
    expect(res.toString()).toEqual("1");
    // #END
  }

  sort() {
    // #TEST Int16Array.sort
    let numbers = new Int16Array([40, 1, 5]);
    numbers.sort();
    expect(numbers.toString()).toEqual("1,5,40");

    numbers.sort((a, b) : number => a - b);
    expect(numbers.toString()).toEqual("1,5,40");
    // #END
  }

  subarray() {
    // #TEST Int16Array.subarray
    let buffer = new ArrayBuffer(16);
    let int16 = new Int16Array(buffer);
    int16.set([1, 2, 3]);
    expect(int16.toString()).toEqual("1,2,3,0,0,0,0,0");

    let sub = int16.subarray(0, 4);
    expect(sub.toString()).toEqual("1,2,3,0");
    // #END
  }

  values() {
    // #TEST Int16Array.values
    let arr = new Int16Array([1, 2, 3]);
    let values = arr.values();
    expect(values.next().value).toEqual(1);
    // #END
  }

  arrayBufferSlice() {

    // #TEST ArrayBuffer.slice with Int16Array
    let buffer = new ArrayBuffer(16);
    let int16 = new Int16Array(buffer);
    int16[4] = 42;
    expect(int16.toString()).toEqual("0,0,0,0,42,0,0,0");

    let res = buffer.slice(8, 12);
    let sliced = new Int16Array(res);
    expect(sliced[0]).toEqual(42);
    // #END

  }
  testSome() {
    // #TEST Int16Array.some
    const int16 = new Int16Array([-10, 20, -30, 40, -50]);
    const positives = new Int16Array([10, 20, 30, 40, 50]);

    expect(int16.some((element : number, index : number, array : Int16Array) : boolean =>
      element < 0
    )).toEqual(true);


    expect(positives.some((element : number, index : number, array : Int16Array) : boolean =>
      element < 0
    )).toEqual(false);
    // #END
  }
  // #endif
}