import {
  describe,
  test,
  expect,
  expectNumber,
  Result
} from './tests.uts'

export class TInt8Array {
  test() {
    // #ifdef APP-ANDROID
    this.testConstructor();
    this.testSet();
    this.testCopyWith();
    this.testEvery();
    this.testFill();
    this.testFilter();
    this.find();
    this.findIndex();
    this.foreach();
    this.iterator();
    this.includes();
    this.indexOf();
    this.join();
    this.keys();
    this.map();
    this.reduce();
    this.reduceRight();
    this.reverse();
    this.slice();
    this.sort();
    this.subarray();
    this.values();
    this.arrayBufferSlice();
    //#endif
  }

// #ifdef APP-ANDROID
  testConstructor() {
    let buffer = new ArrayBuffer(16);
    let int8View = new Int8Array(buffer);
    int8View[5] = 42;
    expect(int8View.toString()).toEqual("0,0,0,0,0,42,0,0,0,0,0,0,0,0,0,0");
  }

  testSet() {
    let int8 = new Int8Array(8);
    var array = [1, 2, 3]
    int8.set(array, 1);
    expect(int8.toString()).toEqual("0,1,2,3,0,0,0,0");
  }

  testCopyWith() {
    console.log("testCopyWith 1")
    let int8 = new Int8Array(8);
    int8.set([1, 2, 3], 1);
    console.log("testCopyWith 1")
    int8.copyWithin(3, 0, 3);
    console.log("testCopyWith 1")
    expect(int8.toString()).toEqual("0,1,2,0,1,2,0,0");
  }

  testEvery() {
    // const isBelowThreshold = (currentValue: number, index: number, array:Int8Array): boolean => currentValue < 40;    
    let result = new Int8Array([12, 5, 8, 130, 44]).every((value: number, _: number, _a: Int8Array): boolean =>
      value < 40); // 
    expect(result).toEqual(false);
  }

  testFill() {
    let int8 = new Int8Array([1, 2, 3]).fill(4);
    expect(int8.toString()).toEqual("4,4,4");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1);
    expect(int8.toString()).toEqual("1,4,4");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1, 2);
    expect(int8.toString()).toEqual("1,4,3");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1, 1);
    expect(int8.toString()).toEqual("1,2,3");

    int8 = new Int8Array([1, 2, 3]).fill(4, -3, -2);
    expect(int8.toString()).toEqual("4,2,3");
  }

  testFilter() {
    // const isBelowThreshold = (currentValue: number, index: number, _): boolean => currentValue >= 10;

    let int8 = new Int8Array([12, 5, 8, 44]).filter((value: number, _: number, _a: Int8Array): boolean =>
      value >= 10);
    expect(int8.toString()).toEqual("12,44");
  }

  find() {
    let int8 = new Int8Array([4, 5, 8, 12]);
    let res = int8.find((value: number, _: number, _a: Int8Array): boolean => value > 5);
    expect(res).toEqual(8);
  }

  findIndex() {
    let int8 = new Int8Array([4, 6, 8, 12]);
    let res = int8.findIndex((value: number, _: number, _a: Int8Array): boolean => value > 100);
    expect(res).toEqual(-1);

    int8 = new Int8Array([4, 6, 7, 120]);
    res = int8.findIndex((value: number, _: number, _a: Int8Array): boolean => value > 100);
    expect(res).toEqual(3);
  }

  foreach() {
    new Int8Array([0, 1, 2, 3]).forEach((value: number, index: number, _: Int8Array) => {
      console.log(`a[${index}] = ${value}`);
    });
  }

  iterator() {
    let arr = new Int8Array([10, 20, 30, 40, 50]);
    let entries = arr.entries();
    expect(entries.next().value[1]).toEqual(10);
    expect(entries.next().value[1]).toEqual(20);
  }

  includes() {
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.includes(2);
    expect(res).toEqual(true);

    res = int8.includes(4);
    expect(res).toEqual(false);

    res = int8.includes(3, 3);
    expect(res).toEqual(false);
  }

  indexOf() {
    let int8 = new Int8Array([2, 5, 9]);
    let res = int8.indexOf(2);
    expect(res).toEqual(0);

    res = int8.indexOf(7);
    expect(res).toEqual(-1);

    res = int8.indexOf(9, 2);
    expect(res).toEqual(2);

    res = int8.indexOf(2, -1);
    expect(res).toEqual(-1);

    res = int8.indexOf(2, -3);
    expect(res).toEqual(0);
  }

  join() {
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.join();
    expect(res).toEqual("1,2,3");

    res = int8.join(" / ");
    expect(res).toEqual("1 / 2 / 3");

    res = int8.join("");
    expect(res).toEqual("123");
  }

  keys() {
    let arr = new Int8Array([10, 20, 30, 40, 50]);
    let keys = arr.keys();
    expect(keys.next().value).toEqual(0);
    expect(keys.next().value).toEqual(1);
    expect(keys.next().value).toEqual(2);
    expect(keys.next().value).toEqual(3);
    expect(keys.next().value).toEqual(4);
  }

  map() {
    let numbers = new Int8Array([1, 4, 9]);
    let doubles = numbers.map((value: number, _: number, _a: Int8Array): number => value * 2);
    expect(numbers.toString()).toEqual("1,4,9");
    expect(doubles.toString()).toEqual("2,8,18");
  }

  reduce() {
    let total = new Int8Array([0, 1, 2, 3]);
    let res = total.reduce((accumulator: number, currentValue: number, _: number, _a: Int8Array):
      number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int8Array([0, 1, 2, 3]);
    res = total.reduce((accumulator: number, currentValue: number, _: number, _a: Int8Array): number =>
      accumulator + currentValue, 8);
    expect(res).toEqual(14);
  }

  reduceRight() {
    let total = new Int8Array([0, 1, 2, 3]);
    let res = total.reduceRight((accumulator: number, currentValue: number, _: number, _a: Int8Array):
      number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int8Array([0, 1, 2, 3]);
    res = total.reduceRight((accumulator: number, currentValue: number, _: number, _a: Int8Array):
      number => accumulator + currentValue, 8);
   
    expect(res).toEqual(14);
  }

  reverse() {
    let int8 = new Int8Array([1, 2, 3]);
    int8.reverse();
    expect(int8.toString()).toEqual("3,2,1");
  }

  slice() {
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.slice(1);
    expect(res.toString()).toEqual("2,3");

    res = int8.slice(2);
    expect(res.toString()).toEqual("3");

    res = int8.slice(-2);
    expect(res.toString()).toEqual("2,3");

    res = int8.slice(0, 1);
    expect(res.toString()).toEqual("1");
  }

  sort() {
    let numbers = new Int8Array([40, 1, 5]);
    numbers.sort();
    expect(numbers.toString()).toEqual("1,5,40");

    numbers.sort((a, b): number => a - b);
    expect(numbers.toString()).toEqual("1,5,40");
  }

  subarray() {
    let buffer = new ArrayBuffer(8);
    let int8 = new Int8Array(buffer);
    int8.set([1, 2, 3]);
    expect(int8.toString()).toEqual("1,2,3,0,0,0,0,0");

    let sub = int8.subarray(0, 4);
    expect(sub.toString()).toEqual("1,2,3,0");
  }

  values() {
    let arr = new Int8Array([1, 2, 3]);
    let values = arr.values();
    expect(values.next().value).toEqual(1);
    expect(values.next().value).toEqual(2);
    expect(values.next().value).toEqual(3);
  }

  arrayBufferSlice() {
    let buffer = new ArrayBuffer(16);
    let int8 = new Int8Array(buffer);
    int8[4] = 42;
    expect(int8.toString()).toEqual("0,0,0,0,42,0,0,0,0,0,0,0,0,0,0,0");

    let res = buffer.slice(4, 12);
    let sliced = new Int8Array(res);
    expect(sliced[0]).toEqual(42);
  }
  // #endif
}