import {
  describe,
  test,
  expect,
  expectNumber,
  Result
} from './tests.uts'

export class TInt8Array {
  test() {
    // #ifdef APP-ANDROID
    this.testConstructor();
    this.testSet();
    this.testCopyWith();
    this.testEvery();
    this.testFill();
    this.testFilter();
    this.find();
    this.findIndex();
    this.foreach();
    this.iterator();
    this.includes();
    this.indexOf();
    this.join();
    this.keys();
    this.map();
    this.reduce();
    this.reduceRight();
    this.reverse();
    this.slice();
    this.sort();
    this.subarray();
    this.values();
    this.arrayBufferSlice();
    //#endif
  }

  // #ifdef APP-ANDROID
  testConstructor() {
    let buffer = new ArrayBuffer(16);
    let int8View = new Int8Array(buffer);
    int8View[5] = 42;
    expect(int8View.toString()).toEqual("0,0,0,0,0,42,0,0,0,0,0,0,0,0,0,0");
  }

  testSet() {
    // #TEST Int8Array.set
    let int8 = new Int8Array(8);
    var array = [1, 2, 3]
    int8.set(array, 1);
    expect(int8.toString()).toEqual("0,1,2,3,0,0,0,0");
    // #END
  }

  testCopyWith() {
    // #TEST Int8Array.copyWith
    let int8 = new Int8Array(8);
    int8.set([1, 2, 3], 1);
    int8.copyWithin(3, 0, 3);
    expect(int8.toString()).toEqual("0,1,2,0,1,2,0,0");
    // #END
  }

  testEvery() {
    // #TEST Int8Array.every
    // const isBelowThreshold = (currentValue: number, index: number, array:Int8Array): boolean => currentValue < 40;    
    let result = new Int8Array([12, 5, 8, 130, 44]).every((value : number, _ : number, _a : Int8Array) : boolean =>
      value < 40);
    expect(result).toEqual(false);
    // #END
  }


  testFill() {
    // #TEST Int8Array.fill
    let int8 = new Int8Array([1, 2, 3]).fill(4);
    expect(int8.toString()).toEqual("4,4,4");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1);
    expect(int8.toString()).toEqual("1,4,4");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1, 2);
    expect(int8.toString()).toEqual("1,4,3");

    int8 = new Int8Array([1, 2, 3]).fill(4, 1, 1);
    expect(int8.toString()).toEqual("1,2,3");

    int8 = new Int8Array([1, 2, 3]).fill(4, -3, -2);
    expect(int8.toString()).toEqual("4,2,3");
    // #END
  }

  testFilter() {
    // #TEST Int8Array.filter
    // const isBelowThreshold = (currentValue: number, index: number, _): boolean => currentValue >= 10;

    let int8 = new Int8Array([12, 5, 8, 44]).filter((value : number, _ : number, _a : Int8Array) : boolean =>
      value >= 10);
    expect(int8.toString()).toEqual("12,44");
    // #END
  }

  find() {
    // #TEST Int8Array.find
    let int8 = new Int8Array([4, 5, 8, 12]);
    let res = int8.find((value : number, _ : number, _a : Int8Array) : boolean => value > 5);
    expect(res).toEqual(8);
    // #END
  }

  findIndex() {
    // #TEST Int8Array.findIndex
    let int8 = new Int8Array([4, 6, 8, 12]);
    let res = int8.findIndex((value : number, _ : number, _a : Int8Array) : boolean => value > 100);
    expect(res).toEqual(-1);

    int8 = new Int8Array([4, 6, 7, 120]);
    res = int8.findIndex((value : number, _ : number, _a : Int8Array) : boolean => value > 100);
    expect(res).toEqual(3);
    // #END
  }

  foreach() {
    // #TEST Int8Array.forEach
    new Int8Array([0, 1, 2, 3]).forEach((value : number, index : number, _a : Int8Array) => {
      console.log(`a[${index}] = ${value}`);
    });
    // #END
  }

  iterator() {
    // #TEST Int8Array.entries
    let arr = new Int8Array([10, 20, 30, 40, 50]);
    let entries = arr.entries();
    expect(entries.next().value[1]).toEqual(10);
    expect(entries.next().value[1]).toEqual(20);
    // #END
  }

  includes() {
    // #TEST Int8Array.includes
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.includes(2);
    expect(res).toEqual(true);

    res = int8.includes(4);
    expect(res).toEqual(false);

    res = int8.includes(3, 3);
    expect(res).toEqual(false);
    // #END
  }

  indexOf() {
    // #TEST Int8Array.indexOf
    let int8 = new Int8Array([2, 5, 9]);
    let res = int8.indexOf(2);
    expect(res).toEqual(0);

    res = int8.indexOf(7);
    expect(res).toEqual(-1);

    res = int8.indexOf(9, 2);
    expect(res).toEqual(2);

    res = int8.indexOf(2, -1);
    expect(res).toEqual(-1);

    res = int8.indexOf(2, -3);
    expect(res).toEqual(0);
    // #END
  }

  join() {
    // #TEST Int8Array.join
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.join();
    expect(res).toEqual("1,2,3");

    res = int8.join(" / ");
    expect(res).toEqual("1 / 2 / 3");

    res = int8.join("");
    expect(res).toEqual("123");
    // #END
  }

  keys() {
    // #TEST Int8Array.keys
    let arr = new Int8Array([10, 20, 30, 40, 50]);
    let keys = arr.keys();
    expect(keys.next().value).toEqual(0);
    expect(keys.next().value).toEqual(1);
    expect(keys.next().value).toEqual(2);
    expect(keys.next().value).toEqual(3);
    expect(keys.next().value).toEqual(4);
    // #END
  }

  map() {
    // #TEST Int8Array.map
    let numbers = new Int8Array([1, 4, 9]);
    let doubles = numbers.map((value : number, _ : number, _a : Int8Array) : number => value * 2);
    expect(numbers.toString()).toEqual("1,4,9");
    expect(doubles.toString()).toEqual("2,8,18");
    // #END
  }

  reduce() {
    // #TEST Int8Array.reduce
    let total = new Int8Array([0, 1, 2, 3]);
    let res = total.reduce((accumulator : number, currentValue : number, _ : number, _a : Int8Array) :
      number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int8Array([0, 1, 2, 3]);
    res = total.reduce((accumulator : number, currentValue : number, _ : number, _a : Int8Array) : number =>
      accumulator + currentValue, 8);
    expect(res).toEqual(14);
    // #END
  }

  reduceRight() {
    // #TEST Int8Array.reduceRight
    let total = new Int8Array([0, 1, 2, 3]);
    let res = total.reduceRight((accumulator : number, currentValue : number, _ : number, _a : Int8Array) :
      number => accumulator + currentValue);
    expect(res).toEqual(6);

    total = new Int8Array([0, 1, 2, 3]);
    res = total.reduceRight((accumulator : number, currentValue : number, _ : number, _a : Int8Array) :
      number => accumulator + currentValue, 8);

    expect(res).toEqual(14);
    // #END
  }

  reverse() {
    // #TEST Int8Array.reverse
    let int8 = new Int8Array([1, 2, 3]);
    int8.reverse();
    expect(int8.toString()).toEqual("3,2,1");
    // #END
  }

  slice() {
    // #TEST Int8Array.slice
    let int8 = new Int8Array([1, 2, 3]);
    let res = int8.slice(1);
    expect(res.toString()).toEqual("2,3");

    res = int8.slice(2);
    expect(res.toString()).toEqual("3");

    res = int8.slice(-2);
    expect(res.toString()).toEqual("2,3");

    res = int8.slice(0, 1);
    expect(res.toString()).toEqual("1");
    // #END
  }

  sort() {
    // #TEST Int8Array.sort
    let numbers = new Int8Array([40, 1, 5]);
    numbers.sort();
    expect(numbers.toString()).toEqual("1,5,40");

    numbers.sort((a, b) : number => a - b);
    expect(numbers.toString()).toEqual("1,5,40");
    // #END
  }

  subarray() {
    // #TEST Int8Array.subarray
    let buffer = new ArrayBuffer(8);
    let int8 = new Int8Array(buffer);
    int8.set([1, 2, 3]);
    expect(int8.toString()).toEqual("1,2,3,0,0,0,0,0");

    let sub = int8.subarray(0, 4);
    expect(sub.toString()).toEqual("1,2,3,0");
    // #END
  }

  values() {
    // #TEST Int8Array.values
    let arr = new Int8Array([1, 2, 3]);
    let values = arr.values();
    expect(values.next().value).toEqual(1);
    expect(values.next().value).toEqual(2);
    expect(values.next().value).toEqual(3);
    // #END
  }

  arrayBufferSlice() {
    
    // #TEST ArrayBuffer.slice
    let buffer = new ArrayBuffer(16);
    let int8 = new Int8Array(buffer);
    int8[4] = 42;
    expect(int8.toString()).toEqual("0,0,0,0,42,0,0,0,0,0,0,0,0,0,0,0");

    let res = buffer.slice(4, 5);
    let sliced = new Int8Array(res);
    expect(sliced[0]).toEqual(42);
    // #END
    
  }

  // #endif
}