import {
  describe,
  test,
  expect,
  Result
} from './tests.uts'

export class TUint8Array {
  test() {
    // #ifdef  APP-ANDROID || WEB

    this.testMAX();
    this.testConstructor();
    this.testSet();
    this.testCopyWith();
    this.testEvery();
    this.testFill();
    this.testFilter();
    this.find();
    this.findIndex();
    this.foreach();
    this.iterator();
    this.includes();
    this.indexOf();
    this.join();
    this.keys();
    this.map();
    this.reduce();
    this.reduceRight();
    this.reverse();
    this.slice();
    this.sort();
    this.subarray();
    this.values();
    this.arrayBufferSlice();
    // #endif
  }
  // #ifdef  APP-ANDROID || WEB

  from() {
    var s = new Set([1, 2, 3]);
    var unit8 = Uint8Array.from(s);
    expect(unit8.toString()).toEqual('1,2,3');
    console.log(unit8.toString())
  }
  testMAX() {
    let uint8 = new Uint8Array(16);
    uint8[0] = 255;
    expect(uint8[0]).toEqual(255);
  }

  testConstructor() {
    let buffer = new ArrayBuffer(16);
    let uint8 = new Uint8Array(buffer);
    uint8[5] = 42;
    expect(uint8.toString()).toEqual("0,0,0,0,0,42,0,0,0,0,0,0,0,0,0,0");
  }

  testSet() {
    // #TEST Uint8Array.set
    let uint8 = new Uint8Array(8);
    var array = [1, 2, 3];
    uint8.set(array, 1);
    console.log(uint8.toString()); // "0,1,2,3,0,0,0,0"
    // #END
    expect(uint8.toString()).toEqual("0,1,2,3,0,0,0,0");
  }

  testCopyWith() {
    // #TEST Uint8Array.copyWithin
    console.log("testCopyWith 1");
    let uint8 = new Uint8Array(8);
    uint8.set([1, 2, 3], 1);
    uint8.copyWithin(3, 0, 3);
    console.log(uint8.toString()); // "0,1,2,0,1,2,0,0"
    // #END
    expect(uint8.toString()).toEqual("0,1,2,0,1,2,0,0");
  }

  testEvery() {
    // #TEST Uint8Array.every
    let result = new Uint8Array([12, 5, 8, 130, 44]).every((value : number, _ : number, _a : Uint8Array) : boolean =>
      value < 40);
    console.log(result); // false
    // #END
    expect(result).toEqual(false);
  }

  testFill() {
    // #TEST Uint8Array.fill
    let uint8 = new Uint8Array([1, 2, 3]).fill(4);
    console.log(uint8.toString()); // "4,4,4"

    uint8 = new Uint8Array([1, 2, 3]).fill(4, 1);
    console.log(uint8.toString()); // "1,4,4"

    uint8 = new Uint8Array([1, 2, 3]).fill(4, 1, 2);
    console.log(uint8.toString()); // "1,4,3"

    uint8 = new Uint8Array([1, 2, 3]).fill(4, 1, 1);
    console.log(uint8.toString()); // "1,2,3"

    uint8 = new Uint8Array([1, 2, 3]).fill(4, -3, -2);
    console.log(uint8.toString()); // "4,2,3"
    // #END
    expect(uint8.toString()).toEqual("4,2,3");
  }

  testFilter() {
    // #TEST Uint8Array.filter
    let uint8 = new Uint8Array([12, 5, 8, 44]).filter((value : number, _ : number, _a : Uint8Array) : boolean => value >= 10);
    console.log(uint8.toString()); // "12,44"
    // #END
    expect(uint8.toString()).toEqual("12,44");
  }

  find() {
    // #TEST Uint8Array.find
    let uint8 = new Uint8Array([4, 5, 8, 12]);
    let res = uint8.find((value : number, _ : number, _a : Uint8Array) : boolean => value > 5);
    console.log(res); // 8
    // #END
    expect(res).toEqual(8);
  }

  findIndex() {
    // #TEST Uint8Array.findIndex
    let uint8 = new Uint8Array([4, 6, 8, 12]);
    let res = uint8.findIndex((value : number, _ : number, _a : Uint8Array) : boolean => value > 100);
    console.log(res); // -1

    let uuint8 = new Uint8Array([4, 6, 7, 120]);
    res = uuint8.findIndex((value : number, _ : number, _a : Uint8Array) : boolean => value > 100);
    console.log(res); // 3
    // #END
    expect(res).toEqual(3);
  }

  foreach() {
    // #TEST Uint8Array.forEach
    new Uint8Array([0, 1, 2, 3]).forEach((value : number, index : number, _ : Uint8Array) => {
      console.log(`a[${index}] = ${value}`);
    });
    // #END
  }

  iterator() {
    // #TEST Uint8Array.entries
    let arr = new Uint8Array([10, 20, 30, 40, 50]);
    let entries = arr.entries();
    let entry = entries.next().value;
    console.log(entry[1]); // 10
    // #END
    expect(entry[1]).toEqual(10);
  }
  includes() {
    // #TEST Uint8Array.includes
    let uint8 = new Uint8Array([1, 2, 3]);
    let res = uint8.includes(2);
    console.log(res); // true

    res = uint8.includes(4);
    console.log(res); // false

    res = uint8.includes(3, 3);
    console.log(res); // false
    // #END
    expect(res).toEqual(false);
  }


  indexOf() {
    // #TEST Uint8Array.indexOf
    let uint8 = new Uint8Array([2, 5, 9]);
    let res = uint8.indexOf(2);
    console.log(res); // 0

    // expect(res).toEqual(0);

    res = uint8.indexOf(7);
    console.log(res); // -1

    // expect(res).toEqual(-1);

    res = uint8.indexOf(9, 2);
    console.log(res); // 2

    // expect(res).toEqual(2);

    res = uint8.indexOf(2, -1);
    console.log(res); // -1

    // expect(res).toEqual(-1);

    res = uint8.indexOf(2, -3);
    console.log(res); // 0
    // #END
    expect(res).toEqual(0);
  }

  join() {
    // #TEST Uint8Array.join
    let uint8 = new Uint8Array([1, 2, 3]);
    let res = uint8.join();
    console.log(res); // "1,2,3"

    // expect(res).toEqual("1,2,3");

    res = uint8.join(" / ");
    console.log(res); // "1 / 2 / 3"

    // expect(res).toEqual("1 / 2 / 3");

    res = uint8.join("");
    console.log(res); // "123"
    // #END
    expect(res).toEqual("123");
  }

  keys() {
    // #TEST Uint8Array.keys
    let arr = new Uint8Array([10, 20, 30, 40, 50]);
    let keys = arr.keys();
    let value = keys.next().value
    console.log(value); // 0
    // #END
    expect(value).toEqual(0);
  }

  map() {
    // #TEST Uint8Array.map
    let numbers = new Uint8Array([1, 4, 9]);
    let doubles = numbers.map((value : number, _ : number, _a : Uint8Array) : number => value * 2);
    console.log(numbers.toString()); // "1,4,9"
    console.log(doubles.toString()); // "2,8,18"
    // #END
    expect(numbers.toString()).toEqual("1,4,9");
    expect(doubles.toString()).toEqual("2,8,18");
  }
  reduce() {
    // #TEST Uint8Array.reduce
    let total = new Uint8Array([0, 1, 2, 3]);
    let res = total.reduce((accumulator : number, currentValue : number, _ : number, _a : Uint8Array) : number =>
      accumulator + currentValue);
    console.log(res); // 6

    // expect(res).toEqual(6);

    total = new Uint8Array([0, 1, 2, 3]);
    res = total.reduce((accumulator : number, currentValue : number, _ : number, _a : Uint8Array) : number =>
      accumulator + currentValue, 8);
    console.log(res); // 14
    // #END
    expect(res).toEqual(14);
  }

  reduceRight() {
    // #TEST Uint8Array.reduceRight
    let total = new Uint8Array([0, 1, 2, 3]);
    let res = total.reduceRight((accumulator : number, currentValue : number, _ : number, _a : Uint8Array) : number =>
      accumulator + currentValue);
    console.log(res); // 6

    // expect(res).toEqual(6);

    total = new Uint8Array([0, 1, 2, 3]);
    res = total.reduceRight((accumulator : number, currentValue : number, _ : number, _a : Uint8Array) : number =>
      accumulator + currentValue, 8);
    console.log(res); // 14
    // #END
    expect(res).toEqual(14);
  }

  reverse() {
    // #TEST Uint8Array.reverse
    let uint8 = new Uint8Array([1, 2, 3]);
    uint8.reverse();
    console.log(uint8.toString()); // "3,2,1"
    // #END
    expect(uint8.toString()).toEqual("3,2,1");
  }

  slice() {
    // #TEST Uint8Array.slice
    let uint8 = new Uint8Array([1, 2, 3]);
    let res = uint8.slice(1);
    console.log(res.toString()); // "2,3"

    // expect(res.toString()).toEqual("2,3");

    res = uint8.slice(2);
    console.log(res.toString()); // "3"

    // expect(res.toString()).toEqual("3");

    res = uint8.slice(-2);
    console.log(res.toString()); // "2,3"

    // expect(res.toString()).toEqual("2,3");

    res = uint8.slice(0, 1);
    console.log(res.toString()); // "1"
    // #END
    expect(res.toString()).toEqual("1");
  }

  sort() {
    // #TEST Uint8Array.sort
    let numbers = new Uint8Array([40, 1, 5]);
    numbers.sort();
    console.log(numbers.toString()); // "1,5,40"

    // expect(numbers.toString()).toEqual("1,5,40");

    numbers.sort((a, b) : number => a - b);
    console.log(numbers.toString()); // "1,5,40"
    // #END
    expect(numbers.toString()).toEqual("1,5,40");
  }

  subarray() {
    // #TEST Uint8Array.subarray
    let buffer = new ArrayBuffer(16);
    let uint8 = new Uint8Array(buffer);
    uint8.set([1, 2, 3]);
    console.log(uint8.toString()); // "1,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0"

    // expect(uint8.toString()).toEqual("1,2,3,0,0,0,0,0,0,0,0,0,0,0,0,0");

    let sub = uint8.subarray(0, 4);
    console.log(sub.toString()); // "1,2,3,0"
    // #END
    expect(sub.toString()).toEqual("1,2,3,0");
  }

  values() {
    // #TEST Uint8Array.values
    let arr = new Uint8Array([1, 2, 3]);
    let values = arr.values();
    let value = values.next().value
    console.log(value); // 1
    // #END
    expect(value).toEqual(1);
  }

  arrayBufferSlice() {
    // #TEST ArrayBuffer.slice
    let buffer = new ArrayBuffer(16);
    let uint8 = new Uint8Array(buffer);
    uint8[4] = 42;
    console.log(uint8.toString()); // "0,0,0,0,42,0,0,0,0,0,0,0,0,0,0,0"

    let res = buffer.slice(4, 12);
    let sliced = new Uint8Array(res);
    console.log(sliced[0]); // 42
    // #END
    expect(sliced[0]).toEqual(42);
  }

  testSome() {
    // #TEST Uint8Array.some
    const uint8 = new Uint8Array([8, 20, 30, 40, 50]);
    const positives = new Uint8Array([10, 20, 30, 40, 50]);
    var res = uint8.some((element : number, index : number, array : Uint8Array) : boolean =>
      element < 10
    );
    console.log('uint8', res); // true

    // expect(res).toEqual(true);

    res = positives.some((element : number, index : number, array : Uint8Array) : boolean =>
      element < 0
    );
    console.log('positives', res); // false
    // #END
    expect(res).toEqual(false);
  }

  // #endif
}